version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./upload:/usr/src/app/upload
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-mongo-user.js:/docker-entrypoint-initdb.d/init-mongo-user.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=openBadges

  mongo-seed:
      image: stefanwalther/mongo-seed
      container_name: mongo-seed
      environment:
        - MONGODB_HOST=mongo
        - MONGODB_PORT=27017
      volumes:
        - ./demo:/data
      depends_on:
        - mongo
      command: [
        "mongoimport --host=mongo \ --db=openBadges --collection=users --file=/data/users.json && mongoimport --host=mongo \ --db=openBadges --collection=projects --file=/data/projects.json && mongoimport --host=mongo \ --db=openBadges --collection=badges --file=/data/badges.json"
      ]
