version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
